#common
IMAGE_PATH = "./images/figures_old/"

CANVAS_WIDTH = 600
CANVAS_HEIGHT = 600
CELL_SIZE = 60

START_X = 10
START_Y = 10

WHITE = True
BLACK = False

#background settings
BACKGROUND_X1 = START_X + 3 * CELL_SIZE
BACKGROUND_Y1 = START_Y + 3 * CELL_SIZE
BACKGROUND_X2 = START_X + 5 * CELL_SIZE
BACKGROUND_Y2 = START_Y + 5 * CELL_SIZE

BACKGROUND_COLOR = 'green'

